### ISSUE TITLE
Multi-GPU Execution Error: Invalid device id

### ISSUE THREAD

**Issue by MaateusSilva** [Atik-Ahamed/TimeMachine#6]
First off, thank you for your excellent work on this project! I've encountered an issue while attempting to utilize the multi-GPU functionality. Specifically, the program runs successfully when GPUs are specified in a sequential order starting from zero using the `--devices` parameter (e.g., "0,1,2"). However, errors occur when the GPUs are specified in a non-sequential order or do not start with zero (e.g., "0,2" or "1,2,3").

Full error message:

```
Traceback (most recent call last):
  File "/home/mateus/repos/forks/TimeMachine/TimeMachine_supervised/run_longExp.py", line 117, in <module>
    exp = Exp(args)  # set experiments
  File "/home/mateus/repos/forks/TimeMachine/TimeMachine_supervised/exp/exp_main.py", line 24, in __init__
    super(Exp_Main, self).__init__(args)
  File "/home/mateus/repos/forks/TimeMachine/TimeMachine_supervised/exp/exp_basic.py", line 10, in __init__
    self.model = self._build_model().to(self.device)
  File "/home/mateus/repos/forks/TimeMachine/TimeMachine_supervised/exp/exp_main.py", line 33, in _build_model
    model = nn.DataParallel(model, device_ids=self.args.device_ids)
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 159, in __init__
    _check_balance(self.device_ids)
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 26, in _check_balance
    dev_props = _get_devices_properties(device_ids)
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/_utils.py", line 734, in _get_devices_properties
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/_utils.py", line 734, in <listcomp>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/_utils.py", line 713, in _get_device_attr
    return get_member(torch.cuda)
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/_utils.py", line 734, in <lambda>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/cuda/__init__.py", line 452, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
Traceback (most recent call last):
  File "/home/mateus/repos/forks/TimeMachine/TimeMachine_supervised/run_longExp.py", line 117, in <module>
    exp = Exp(args)  # set experiments
  File "/home/mateus/repos/forks/TimeMachine/TimeMachine_supervised/exp/exp_main.py", line 24, in __init__
    super(Exp_Main, self).__init__(args)
  File "/home/mateus/repos/forks/TimeMachine/TimeMachine_supervised/exp/exp_basic.py", line 10, in __init__
    self.model = self._build_model().to(self.device)
  File "/home/mateus/repos/forks/TimeMachine/TimeMachine_supervised/exp/exp_main.py", line 33, in _build_model
    model = nn.DataParallel(model, device_ids=self.args.device_ids)
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 159, in __init__
    _check_balance(self.device_ids)
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 26, in _check_balance
    dev_props = _get_devices_properties(device_ids)
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/_utils.py", line 734, in _get_devices_properties
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/_utils.py", line 734, in <listcomp>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/_utils.py", line 713, in _get_device_attr
    return get_member(torch.cuda)
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/_utils.py", line 734, in <lambda>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/cuda/__init__.py", line 452, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
Traceback (most recent call last):
  File "/home/mateus/repos/forks/TimeMachine/TimeMachine_supervised/run_longExp.py", line 117, in <module>
    exp = Exp(args)  # set experiments
  File "/home/mateus/repos/forks/TimeMachine/TimeMachine_supervised/exp/exp_main.py", line 24, in __init__
    super(Exp_Main, self).__init__(args)
  File "/home/mateus/repos/forks/TimeMachine/TimeMachine_supervised/exp/exp_basic.py", line 10, in __init__
    self.model = self._build_model().to(self.device)
  File "/home/mateus/repos/forks/TimeMachine/TimeMachine_supervised/exp/exp_main.py", line 33, in _build_model
    model = nn.DataParallel(model, device_ids=self.args.device_ids)
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 159, in __init__
    _check_balance(self.device_ids)
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 26, in _check_balance
    dev_props = _get_devices_properties(device_ids)
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/_utils.py", line 734, in _get_devices_properties
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/_utils.py", line 734, in <listcomp>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/_utils.py", line 713, in _get_device_attr
    return get_member(torch.cuda)
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/_utils.py", line 734, in <lambda>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/cuda/__init__.py", line 452, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
Traceback (most recent call last):
  File "/home/mateus/repos/forks/TimeMachine/TimeMachine_supervised/run_longExp.py", line 117, in <module>
    exp = Exp(args)  # set experiments
  File "/home/mateus/repos/forks/TimeMachine/TimeMachine_supervised/exp/exp_main.py", line 24, in __init__
    super(Exp_Main, self).__init__(args)
  File "/home/mateus/repos/forks/TimeMachine/TimeMachine_supervised/exp/exp_basic.py", line 10, in __init__
    self.model = self._build_model().to(self.device)
  File "/home/mateus/repos/forks/TimeMachine/TimeMachine_supervised/exp/exp_main.py", line 33, in _build_model
    model = nn.DataParallel(model, device_ids=self.args.device_ids)
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 159, in __init__
    _check_balance(self.device_ids)
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 26, in _check_balance
    dev_props = _get_devices_properties(device_ids)
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/_utils.py", line 734, in _get_devices_properties
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/_utils.py", line 734, in <listcomp>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/_utils.py", line 713, in _get_device_attr
    return get_member(torch.cuda)
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/_utils.py", line 734, in <lambda>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/home/mateus/miniconda3/envs/TimeMachine_supervised/lib/python3.10/site-packages/torch/cuda/__init__.py", line 452, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
```

My `etth1.sh` file:

```bash
if [ ! -d "./logs" ]; then
    mkdir ./logs
fi

if [ ! -d "./logs/LongForecasting" ]; then
    mkdir ./logs/LongForecasting
fi
if [ ! -d "./csv_results" ]; then
    mkdir ./csv_results
fi
if [ ! -d "./results" ]; then
    mkdir ./results
fi
if [ ! -d "./test_results" ]; then
    mkdir ./test_results
fi
model_name=TimeMachine

root_path_name=../data/ETT-small
data_path_name=ETTh1.csv
model_id_name=ETTh1
data_name=ETTh1

rin=1
random_seed=2024
one=96
two=192
three=336
four=720
residual=1
fc_drop=0.7
dstate=256
dconv=2
for seq_len in 96
do
    for pred_len in 96 192 336 720
    do  
        for e_fact in 1
        do

            if [ $pred_len -eq $one ]
            then
                n1=512
                n2=32
            fi
            if [ $pred_len -eq $two ]
            then
                n1=512
                n2=64
            fi
            if [ $pred_len -eq $three ]
            then
                n1=512
                n2=128
            fi
            if [ $pred_len -eq $four ]
            then
                n1=128
                n2=16
            fi
            python -u run_longExp.py \
            --random_seed $random_seed \
            --is_training 1 \
            --root_path $root_path_name \
            --data_path $data_path_name \
            --model_id $model_id_name_$seq_len'_'$pred_len \
            --model $model_name \
            --data $data_name \
            --features M \
            --seq_len $seq_len \
            --pred_len $pred_len \
            --enc_in 7 \
            --n1 $n1 \
            --n2 $n2 \
            --dropout $fc_drop\
            --revin 1\
            --ch_ind 1\
            --residual $residual\
            --dconv $dconv \
            --d_state $dstate\
            --e_fact $e_fact\
            --des 'Exp' \
            --train_epochs 100\
            --itr 1 --batch_size 64 --learning_rate 0.001 --use_multi_gpu --devices  "1,2" >logs/LongForecasting/$model_name'_'$model_id_name'_'$seq_len'_'$pred_len'_'$n1'_'$n2'_'$fc_drop'_'$rin'_'$residual'_'$dstate'_'$dconv'_'$e_fact.log 
        
        done        
    done
done
```

I appreciate any guidance or updates you can provide on this issue. Thank you!

**Comment by Atik-Ahamed** [comment]
Hi @MaateusSilva,
Thank you for your valuable feedback and for trying our work. 
Can you please try using the following modifications:

```
 CUDA_VISIBLE_DEVICES=1,2
            python -u run_longExp.py \
..... _rest of the scripts.._
--devices  "0,1"....
```
Please refer to this issue mentioned here: https://github.com/pytorch/pytorch/issues/1280
You may find more details on the multi-gpu environment scenario.

**Comment by MaateusSilva** [comment]
@Atik-Ahamed, thank you for the feedback! Adding `export CUDA_VISIBLE_DEVICES=3,4` worked perfectly! Also, thanks for linking to the other issue to provide context.
